#!/bin/bash/
# Get the list of the network interfaces of the machine without displaying
# any detail for these interfaces. Only the list of names.

# -l flag is used to list all available interfaces on the system with no
# additional info.
ifconfig -l
