#!/bin/bash/

# What command can you use to rename your system?

# first we need to become a root user with sudo command then
# use hotnamectl command. then check if the change happened
# with hostnamectl command.

sudo hostnamectl set-hostname new-name
