#!/bin/bash/

# What command gives you the time since your system was last booted?

uptime

# uptime shows the amount of time that has passed since the system has been
# booted or how long the system has been running. It does not tell you the
# system clock or system boot time