#!/bin/bash/

# Name the command that lists the partition tables of drives?

lsblk

# The lsblk command lists all the block devices of your system
# along with their logical partitions.
# block devices are special files that refer to or represent a device (which
# could be anything from a hard drive to a USB drive)