#!/bin/bash/

# Name the command that displays the available space left and used on the system
in an humanly understandable way

df -h

# The df command stands for "disk-free," and shows available and used disk
# space on the Linux system.
# df -h shows disk space in human-readable format